#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    Ground_Branch               |
 * | Version: 10.09.2025                  |
 * | Date:    09/10/2025                  |
 * ----------------------------------------
 */

#include <cstdint>
#include <vector>
#include <string>

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Engine
{
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
