#pragma once

/**
 * ----------------------------------------
 * |        Generated By CheatGear        |
 * ----------------------------------------
 * | Game:    Ground_Branch               |
 * | Version: 10.09.2025                  |
 * | Date:    09/10/2025                  |
 * ----------------------------------------
 */

#define UE4
#define GAME_MODULE_NAME L"GroundBranch-Win64-Shipping.exe"
#define NAMES_OFFSET 0x6B5D8C0
#define OBJECTS_OFFSET 0x6B99F30
#define WORLD_OFFSET 0x6CE03A0
#define PROCESS_EVENT_INDEX 0x44
#define CREATE_DEFAULT_OBJECT_INDEX 0x74
#define POST_RENDER_INDEX 0x3B
#define GET_BONE_MATRIX_OFFSET 0x00
#define GET_VIEW_POINT_INDEX 0x00
#define GET_PLAYER_VIEW_POINT_OFFSET 0x00

#ifdef _MSC_VER
    #pragma pack(push, 0x01)
#endif

namespace CG::Global
{
}

#ifdef _MSC_VER
    #pragma pack(pop)
#endif
